/:
  controller: Base
  action: index

/signup:
  controller: Auth
  action: signupForm

/register:
  controller: Auth
  action: signup

/login:
  controller: Auth
  action: loginForm

/login-post:
  controller: Auth
  action: login

/logout:
  controller: Auth
  action: logout

/dashboard:
  controller: Base
  action: dashboard

/activation:
  controller: Auth
  action: activation

/forgot:
  controller: Auth
  action: forgotForm

/forgot-post:
  controller: Auth
  action: forgot

/reset-password:
  controller: Auth
  action: resetForm

/reset-password-post:
  controller: Auth
  action: reset

/pages:
  controller: "PageController"
  action: "index"

/create:
  controller: "PageController"
  action: "createForm"

/create_post:
  controller: "PageController"
  action: "create"

/edit:
  controller: "PageController"
  action: "editForm"

/update:
  controller: "PageController"
  action: "update"

/delete:
  controller: "PageController"
  action: "delete"
